Init vx-delegate
VeriSilicon/tensorflow pull request #19
Opened 2021-01-12 07:10 UTC by liyuenan2333

Signed-off-by: xiang.zhang <xiang.zhang@verisilicon.com>

2021-01-12 12:45 UTC, sunshinemyson requested changes
1. license missed
2. const ref missed
3. reorg namespace

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/delegate_main.cc
> +  // TODO(derekjchow): Return error if compilation failed.
remove this? already fatal in line 501

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/delegate_main.cc
> +      LOG(FATAL) << "Disaster!";
more descriptive log

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/delegate_main.cc
> +    tensor->CopyDataToTensor(const_cast<void*>(tensor_data));
check return value

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/delegate_main.cc
> +    LOG(FATAL) << "Failed to verify graph";
wrong message. should be "failed to run graph"

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/delegate_main.cc
> +      LOG(FATAL) << "Disaster!";
descriptive message

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/delegate_main.cc
> +    tensor->CopyDataFromTensor(tensor_data);
check return value

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/delegate_main.cc
> +      LOG(FATAL) << "Disaster!";
descriptive error message

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/delegate_main.cc
> +  // Mark all the data buffers that need copying back.
remove unused code

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/delegate_main.h
> +#ifndef OVXLIBXX_DELEGATE_H_
guard : TENSORFLOW_LITE_DELEGATES_VX_DELEGAGE_DELEGATE_MAIN_H

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/delegate_main.h
> +namespace ovxlibxx_delegate {
reorg namespace

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/op_map.cc
> +    std::shared_ptr<tim::vx::Tensor> original_output_tensor) {
const .. &

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/op_map.cc
> +    default:
move default to the end?

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/op_map.cc
> +    std::vector<uint32_t> perm) {
const .. &

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/op_map.cc
> +    std::shared_ptr<tim::vx::Tensor> original_input_tensor,
const ref

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/op_map.cc
> +  auto temp = delegate->GetGraph()->CreateTensor(
don't name it as temp

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/op_map.cc
> +    std::shared_ptr<tim::vx::Tensor> original_output_tensor,
const ref

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/op_map.cc
> +
only single empty line is allowed

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/op_map.cc
> +  ReduceOpMapper(std::string name) : name_(name) {}
const ref

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/op_map.cc
> +      std::vector<std::shared_ptr<tim::vx::Tensor>>& inputs,
const ?

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/op_map.h
> +namespace ovxlibxx_op_map {
vx::delegate::mapping

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/util.h
> +#ifndef OVXLIBXX_UTIL_H_
GUARD name

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/util.h
> +namespace ovxlibxx_util {
vx::delegate::utils

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/util.h
> +#endif
new line

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/kernels/test_util.cc
> +    // TODO warning or error
log(FATAL) << "Don't setup ..."

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/kernels/test_util.cc
> +void SingleOpModel::SetForceUseVxDelegate(bool use_vsi) {
rename use_vsi to use_vx_delegate

2021-01-12 12:45 UTC, sunshinemyson commented on tensorflow/lite/kernels/test_util.h
> +  static void SetForceUseVxDelegate(bool use_vsi);
rename use_vsi to use_vx_deleagate

2021-01-13 10:22 UTC, liyuenan2333 commented on tensorflow/lite/delegates/vx-delegate/util.h
> +#endif
what it means?

2021-01-13 10:32 UTC, liyuenan2333 commented on tensorflow/lite/kernels/test_util.cc
> +    // TODO warning or error
what it mean?

2021-01-14 06:19 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/delegate_main.h
> +    std::vector<int> states;
//!< for recurrent operation: LSTM, RNN

2021-01-14 06:22 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/delegate_main.h
> +  Delegate();
make it private

2021-01-14 07:11 UTC, sunshinemyson requested changes

2021-01-14 07:11 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/op_map.cc
> +      std::vector<std::shared_ptr<tim::vx::Tensor>>& outputs,
const ref

2021-01-14 07:11 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/op_map.cc
> +typedef std::function<std::unique_ptr<IOpMapper>()> createIOpMapItemFunc;
using

2021-01-14 07:11 UTC, sunshinemyson commented on tensorflow/lite/delegates/vx-delegate/op_map.cc
> +
blank line

2021-01-15 16:35 UTC, sunshinemyson approved these changes

2021-01-15 16:36 UTC, merged